require_relative 'db'
require 'sequel/model'
require_relative "models/song"
require_relative "models/unique_view"
require_relative "models/tag"
require_relative "models/rating"
require_relative "models/genre"
require_relative "models/user"
require_relative "models/error"
